var menulist = {
    "data": [
        {
            "id": 1,
            "parentId": 0,
            "resDesc": "AI标注菜单",
            "resName":"AI标注菜单",
            'isHidden':1,
            "resType":"template",
            "resUrl": "#",
        },
        {
            "id": 17,
            "parentId": 1,
            "resDesc": "AI标注菜单",
            "resName":"AI标注菜单",
            'isHidden':1,
            "resType":"menu",
            "resUrl": "#",
        },
        {
            "id": 3,
            "parentId": 1,
            "resDesc": "系统管理",
            "resName":"系统管理",
            'isHidden':1,
            "resType":"menu",
            "resUrl": "#",
        },
        {
            "id": 25,
            "parentId": 3,
            "resName":"品牌导入",
            'isHidden':1,
            "resType":"page",
            "resPage": "/importBrand",
        },
        {
            "id": 18,
            "parentId": 17,
            "resName":"标签管理",
            'isHidden':1,
            "resType":"page",
            "resPage": "/labelManagement",
        },
        {
            "id": 19,
            "parentId": 17,
            "resName":"数据集管理",
            'isHidden':1,
            "resType":"page",
            "resPage": "/datasetManagement",
        },
        {
            "id": 20,
            "parentId": 17,
            "resName":"图片标注",
            'isHidden':1,
            "resType":"page",
            "resPage": "/imageOverlays",
        },
        {
            "id": 21,
            "parentId": 17,
            "resName":"图片审核",
            'isHidden':1,
            "resType":"page",
            "resPage": "/imageAudit",
        },
        {
            "id": 22,
            "parentId": 17,
            "resName":"数据集下载",
            'isHidden':1,
            "resType":"page",
            "resPage": "/datasetDownload",
        },
        {
            "id": 23,
            "parentId": 3,
            "resName":"人员维护",
            'isHidden':1,
            "resType":"page",
            "resPage": "/personnelMaintenance",
        },
    ]
}

export default menulist